---
title: "Course Home"
author: "ACCE Research Data and Project Management"
date: "01-02 May 2018, TUoS"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: flatly
    highlight: textmate
---


## Description

In order to ensure robustness of outputs and maximise the benefits of ACCE research to future researchers and society more generally, it is important to share the underlying code and data. But for sharing to have any impact, such materials need to be created FAIR (findable, accessible, interoperable, reusable), i.e. they must be adequately described, archived, and made discoverable to an appropriate standard. Additionally, if analyses are to be deemed robust, they must be at the very least reproducible but ideally well documented and reviewable. Such skills are increasingly becoming recognised as standard for modern open, reproducible and collaborative computational research. Fortunately, in recent years, they have been made increasingly accessible through advanced digital tools.

The workshop is designed to be relevant to students with a wide range of backgrounds, working with anything from relatively small sets of data collected from field or experimental observations, to those taking a more computational approach and harnessing the power of big data. It also builds on the Quantitative Skills Workshop by focusing on data and project management through R and Rstudio. The course will introduce students to best practice in research project management and equip them with modern tools and techniques for managing their computational workflows to their full potential.

### By the end of the workshop, participants will be able to:

Understand the basics of good research data management and be able to produce tidy, clean datasets with appropriate metadata.
Manage their computational projects for reproducibility, reuse and collaboration.
Use version control to track the evolution of research projects.
Use modern tools to document code, analyses and data and produce reproducible reports.
Be able to publish, share materials and collaborate through the web.
Understand why this all matters!

***

[Software Setup Instructions](http://annakrystalli.me/ACCE/setup)

***

## **Schedule**

### Tue May 1st

- [Introduction](http://annakrystalli.me/ACCE/introduction.html)
- [Basic Data Hygiene](http://annakrystalli.me/ACCE/RDM_intro.html)
- [Tidy Data](http://annakrystalli.me/ACCE/tidy-data.html)

- [Good Filenaming](http://annakrystalli.me/ACCE/filenaming.html)
- [Metadata & Data Documentation](http://annakrystalli.me/ACCE/metadata.html)

- [Project Management](http://annakrystalli.me/ACCE/project_man.html)

### Wed May 2nd

- [Literate Programming](http://annakrystalli.me/ACCE/literate-prog.html)

- [Version Control through Git](http://annakrystalli.me/ACCE/git.html)

- [Collaborative through GitHub](http://annakrystalli.me/ACCE/collab_gh_intro.html)

- [Bringing it all together](http://annakrystalli.me/ACCE/outro.html)




